name: 'Check spelling'

on:
  push:
    branches:
      - main

jobs:
  spellcheck:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v2
